# Dockerfile pour l'application Vue.js
FROM node:14

# Définir le répertoire de travail pour l'application Vue.js
WORKDIR /app/vue

# Copier les fichiers de l'application Vue.js
COPY ./Vue.git .

# Installer les dépendances pour l'application Vue.js
RUN npm install

# Construire l'application Vue.js
RUN npm run build

# Exposer le port sur lequel l'application Vue.js s'exécute
EXPOSE 8080

# Commande pour démarrer l'application Vue.js
CMD ["npm", "start"]
